### PR TITLE
fix: Fields / async-select should trigger onChange

### LINKED ISSUE #14: Required field for Async-select
Currently not working. It is required, but doesn't pick up on a value being there

image

image

### PR DESCRIPTION
**Pull request by jonashaefele**
Closes #14 (at least it calls onChange properly and forwards the data from react-select)
We might need to check if it saves/retrieves the right data from the DB, on the app side.

### CODE REVIEW

**Comment by luckylwk** [comment]
Doesn't work for some reason. The fields wrapper does not pickup the required field is populated. 

image

I'll add some logging etc. later this morning and try to see what is not going where.

**Comment by luckylwk** [comment]
Leave it with me for now, its not worth you spending short amounts of time on this for now :)

**Comment by jonashaefele** [comment]
Weird it worked for me. Classic.

|| Sent from my phone

**Comment by luckylwk** [comment]
Can you try something for me:
- Backend `luuk/feat-review-feedback` and run `make dev/remote`
- Frontend `master`, add the link to the updated HDS, run `make dev`

Try confirming `http://localhost:3000/booking/h/5da68d21ee15a5001c538b6a`

**Pull request merged**
