### PR TITLE
Design Iteration #1

### PR DESCRIPTION
**Pull request by luckylwk**
- add: more spacious design for Form elements
- update: `fontSizes` scale (bigger base font size)
- add: hide diffs of generated  files in `lib` and `es` folders for PR readability
- add: `borderWidths` `none`,`small`,`base`,`large`

### CODE REVIEW

**Comment by luckylwk** [comment]
@jonashaefele this is now rebased of #42

**Comment by luckylwk** [comment]
Checked the design iteration and I like it 👍  @jonashaefele 

Let's keep experimenting with different fonts for a separate PR.

If you can check my other PR and then we can merge this one in and close both and also bump the version to `v1.2`

**Comment by luckylwk** [comment]
image

Want to make a few changes to the font-weight. It seems off between select and input

**Comment by jonashaefele** [comment]
yeah, not sure where the weird new font-weights came in. we didn't have light fonts, now they are suddenly there. I say you added light and medium to the `fontWeights` scale, but didn't think you used them yet?

I'll check what happened there. Should be ready by the time you get up tomorrow.

**Pull request merged**
